### ISSUE TITLE
Error report in send_message call

### ISSUE THREAD

**Issue by kyhhdm** [st1vms/unofficial-claude2-api#14]
I got an error today in send_message call as:
Error code 403, response -> {"error":{"type":"permission_error","message":"Endpoint disabled"}}

it seems that claude.ai upgrade from "https://claude.ai//api/append_message" to "https://claude.ai/api/organizations/$organizationID/chat_conversations/$chatID/completion",

FYI

**Comment by st1vms** [comment]
@kyhhdm Thanks a lot for letting me notice!

I'm going to work on a new PR as soon as possible.

**Comment by st1vms** [comment]
@kyhhdm Can you please give a quick try to #15 ?

Waiting for confirmations in order to merge and release the 0.2.8 version.
