### ISSUE TITLE
Claude 3?

### ISSUE THREAD

**Issue by ermaxinc** [st1vms/unofficial-claude2-api#17]
When should we expect an update for claude 3?

**Comment by st1vms** [comment]
@ermaxinc 
I'm not actually aware of a Claude 3 update...

If it's just the model name updated, then it's just a matter of changing `model_name` paramater in `ClaudeAPIClient`.

May require more changes but I'm not sure and don't have much time to verify right now...

If you're willing to post the relevant captured request for `send_message` and try changing the client parameter, it would help me a lot.

**Comment by st1vms** [comment]
Apparently, it seems they dropped that parameter, probably this API should avoid setting it by default if no `model_name` was provided.

I'm working on a PR for this...
