### ISSUE TITLE
Unable to prepare file attachment

### ISSUE THREAD

**Issue by Randomboiii03** [st1vms/unofficial-claude2-api#4]
I tried uploading PDF file, which is not more than 10MB and give me this: `[403] Unable to prepare file attachment -> myPDF.pdf`
when I tried uploading it directly to the web to check if my PDF will upload, it uploads.

**Comment by st1vms** [comment]
@Randomboiii03 

Version 0.2.2 was released today, the 403 error seems to be fixed, also the library was updated to reflect new Claude 2.1 model!

Please let me know if this solves your issues...
