### ISSUE TITLE
RuntimeError: Cannot retrieve Organization ID

### ISSUE THREAD

**Issue by roaringmyshallowwater** [st1vms/unofficial-claude2-api#7]
RuntimeError: Cannot retrieve Organization ID!
{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}

I've tried a couple of unofficial claude2 api projects and I always get this error. It looks like claude has disabled analog browser access? I'm curious to know if a solution exists.

**Comment by st1vms** [comment]
Duplicate of #4 and #5 

Closing this, as there is no alternative rather than trying with a different location ( VPN set to US/UK )
