### ISSUE TITLE
curl_cffi: NotImplementedError: Files has not been implemented.

### ISSUE THREAD

**Issue by gadelkareem** [st1vms/unofficial-claude2-api#9]
Hitting this issue https://github.com/yifeikong/curl_cffi/issues/105

Are file uploads not possible?

**Comment by st1vms** [comment]
Could you be more specific? What's not working as expected? You mean the http_post call on line 266 that uses files parameter?

**Comment by st1vms** [comment]
Could you be more specific? What's not working as expected? You mean the http_post call on line 266 that uses files parameter?

As I remember there should be no problems in using that parameter with curl_cffi

**Comment by gadelkareem** [comment]
> You mean the http_post call on line 266 that uses files parameter?
Yes, exactly. If I add an attachment file path then I get that not implemented exception. Not sure if it is just my config.
curl-cffi==0.5.10

**Comment by st1vms** [comment]
Fixed in [v0.2.5](https://github.com/st1vms/unofficial-claude2-api/releases/tag/0.2.5).
Closing this issue...
